Repository Team-Tiki/TIKI_SERVER, pull requests merged in 2024-12, with the labels that each got.

#185 [FEAT] 워크스페이스 설정 기능들 추가
  src/main/java/com/tiki/server/document/service/DocumentService.java
  src/main/java/com/tiki/server/external/controller/S3Controller.java
  src/main/java/com/tiki/server/external/service/S3Service.java
  src/main/java/com/tiki/server/external/util/S3Handler.java
  src/main/java/com/tiki/server/folder/service/FolderService.java
  src/main/java/com/tiki/server/memberteammanager/adapter/MemberTeamManagerFinder.java
  src/main/java/com/tiki/server/memberteammanager/controller/MemberTeamController.java
  src/main/java/com/tiki/server/memberteammanager/controller/dto/request/UpdateTeamMemberNameRequest.java
  src/main/java/com/tiki/server/memberteammanager/entity/MemberTeamManager.java
  src/main/java/com/tiki/server/memberteammanager/message/SuccessMessage.java
  src/main/java/com/tiki/server/memberteammanager/service/MemberTeamManagerService.java
  src/main/java/com/tiki/server/memberteammanager/service/dto/response/MemberTeamPositionGetResponse.java
  src/main/java/com/tiki/server/note/service/NoteService.java
  src/main/java/com/tiki/server/team/controller/TeamController.java
  src/main/java/com/tiki/server/team/controller/dto/request/UpdateTeamIconRequest.java
  src/main/java/com/tiki/server/team/controller/dto/request/UpdateTeamNameRequest.java
  src/main/java/com/tiki/server/team/entity/Team.java
  src/main/java/com/tiki/server/team/message/SuccessMessage.java
  src/main/java/com/tiki/server/team/service/TeamService.java
  src/main/java/com/tiki/server/timeblock/service/TimeBlockService.java
Labels: feat

#187 [FEAT] 폴더 이름 수정
  src/main/java/com/tiki/server/folder/controller/FolderController.java
  src/main/java/com/tiki/server/folder/dto/request/FolderNameUpdateRequest.java
  src/main/java/com/tiki/server/folder/entity/Folder.java
  src/main/java/com/tiki/server/folder/message/SuccessMessage.java
  src/main/java/com/tiki/server/folder/service/FolderService.java
Labels: feat

#181 [FEAT] 팀 탈퇴 기능 구현
  src/main/java/com/tiki/server/external/service/S3Service.java
  src/main/java/com/tiki/server/external/util/S3Handler.java
  src/main/java/com/tiki/server/folder/dto/request/FolderNameUpdateRequest.java
  src/main/java/com/tiki/server/memberteammanager/controller/MemberTeamManagerController.java
  src/main/java/com/tiki/server/memberteammanager/service/MemberTeamManagerService.java
  src/main/java/com/tiki/server/note/adapter/NoteFinder.java
  src/main/java/com/tiki/server/note/entity/Note.java
  src/main/java/com/tiki/server/note/repository/NoteRepository.java
  src/main/java/com/tiki/server/team/message/ErrorCode.java
  src/main/java/com/tiki/server/team/service/TeamService.java
Labels: feat

#196 [FEAT] 타임 블록 api 수정
  src/main/java/com/tiki/server/document/adapter/DocumentDeleter.java
  src/main/java/com/tiki/server/document/adapter/DocumentFinder.java
  src/main/java/com/tiki/server/document/adapter/DocumentSaver.java
  src/main/java/com/tiki/server/document/controller/DocumentController.java
  src/main/java/com/tiki/server/document/controller/docs/DocumentControllerDocs.java
  src/main/java/com/tiki/server/document/dto/request/DocumentCreateRequest.java
  src/main/java/com/tiki/server/document/entity/DeletedDocument.java
  src/main/java/com/tiki/server/document/entity/Document.java
  src/main/java/com/tiki/server/document/repository/DocumentRepository.java
  src/main/java/com/tiki/server/document/service/DocumentService.java
  src/main/java/com/tiki/server/documenttimeblockmanager/adapter/DTBAdapter.java
  src/main/java/com/tiki/server/documenttimeblockmanager/entity/DTBManager.java
  src/main/java/com/tiki/server/documenttimeblockmanager/repository/DTBRepository.java
  src/main/java/com/tiki/server/external/dto/request/S3DeleteRequest.java
  src/main/java/com/tiki/server/external/service/S3Service.java
  src/main/java/com/tiki/server/folder/controller/docs/FolderControllerDocs.java
  src/main/java/com/tiki/server/note/service/NoteService.java
  src/main/java/com/tiki/server/timeblock/adapter/TimeBlockFinder.java
  src/main/java/com/tiki/server/timeblock/controller/TimeBlockController.java
  src/main/java/com/tiki/server/timeblock/controller/docs/TimeBlockControllerDocs.java
  src/main/java/com/tiki/server/timeblock/dto/request/TimeBlockCreateRequest.java
  src/main/java/com/tiki/server/timeblock/dto/response/TimeBlockDetailGetResponse.java
  src/main/java/com/tiki/server/timeblock/message/ErrorCode.java
  src/main/java/com/tiki/server/timeblock/message/SuccessMessage.java
  src/main/java/com/tiki/server/timeblock/repository/TimeBlockRepository.java
  src/main/java/com/tiki/server/timeblock/service/TimeBlockService.java
  src/main/java/com/tiki/server/timeblock/service/dto/DocumentTagInfo.java
Labels: feat

#193 [FEAT] 워크스페이스 설정 로직
  src/main/java/com/tiki/server/auth/controller/docs/AuthControllerDocs.java
  src/main/java/com/tiki/server/document/entity/Document.java
  src/main/java/com/tiki/server/document/repository/DocumentRepository.java
  src/main/java/com/tiki/server/document/service/DocumentService.java
  src/main/java/com/tiki/server/external/controller/FileHandlerController.java
  src/main/java/com/tiki/server/external/controller/docs/FileeHandlerControllerDocs.java
  src/main/java/com/tiki/server/external/service/FileHandlerService.java
  src/main/java/com/tiki/server/external/util/AwsHandler.java
  src/main/java/com/tiki/server/memberteammanager/controller/MemberTeamController.java
  src/main/java/com/tiki/server/memberteammanager/message/SuccessMessage.java
  src/main/java/com/tiki/server/memberteammanager/service/MemberTeamManagerService.java
  src/main/java/com/tiki/server/memberteammanager/service/dto/response/MemberTeamInformGetResponse.java
  src/main/java/com/tiki/server/memberteammanager/service/dto/response/MemberTeamPositionGetResponse.java
  src/main/java/com/tiki/server/team/controller/TeamController.java
  src/main/java/com/tiki/server/team/dto/request/TeamMemberAndTeamInformUpdateRequest.java
  src/main/java/com/tiki/server/team/dto/request/TeamMemberAndTeamInformUpdateServiceRequest.java
  src/main/java/com/tiki/server/team/dto/request/UpdateTeamIconRequest.java
  src/main/java/com/tiki/server/team/dto/request/UpdateTeamNameRequest.java
  src/main/java/com/tiki/server/team/entity/Team.java
  src/main/java/com/tiki/server/team/message/SuccessMessage.java
  src/main/java/com/tiki/server/team/service/TeamService.java
  src/main/java/com/tiki/server/team/service/dto/response/TeamInformGetResponse.java
  src/main/java/com/tiki/server/timeblock/message/ErrorCode.java
  src/main/java/com/tiki/server/timeblock/repository/TimeBlockRepository.java
Labels: feat

#198 [FEAT] Note 스웨거 작업
  src/main/java/com/tiki/server/note/controller/NoteController.java
  src/main/java/com/tiki/server/note/controller/docs/NoteControllerDocs.java
  src/main/java/com/tiki/server/note/service/dto/response/NoteDetailGetServiceResponse.java
Labels: feat

#200 [FIX] 스웨거 동일 네이밍 응답 데이터 매칭 오류
  src/main/resources/application-dev.yml
Labels: fix

#202 [FEAT] 드라이브 조회
  src/main/java/com/tiki/server/auth/controller/docs/AuthControllerDocs.java
  src/main/java/com/tiki/server/document/controller/docs/DocumentControllerDocs.java
  src/main/java/com/tiki/server/document/dto/response/DocumentsGetResponse.java
  src/main/java/com/tiki/server/drive/controller/DriveController.java
  src/main/java/com/tiki/server/drive/controller/docs/DriveControllerDocs.java
  src/main/java/com/tiki/server/drive/dto/DriveGetResponse.java
  src/main/java/com/tiki/server/drive/message/SuccessMessage.java
  src/main/java/com/tiki/server/drive/service/DriveService.java
  src/main/java/com/tiki/server/folder/controller/docs/FolderControllerDocs.java
  src/main/java/com/tiki/server/folder/dto/response/FoldersGetResponse.java
  src/main/java/com/tiki/server/member/controller/docs/MemberControllerDocs.java
  src/main/java/com/tiki/server/timeblock/dto/response/TimeBlockDetailGetResponse.java
  src/main/resources/application-dev.yml
Labels: feat

#204 [CHORE] oas 도입 관련 이슈 해결 테스트
  src/main/java/com/tiki/server/folder/dto/request/FolderNameUpdateRequest.java
Labels: chore

#206 [CHORE] 클라 oas 도입 관련 이슈 해결
  src/main/java/com/tiki/server/auth/dto/request/SignInRequest.java
  src/main/java/com/tiki/server/auth/dto/response/ReissueGetResponse.java
  src/main/java/com/tiki/server/auth/dto/response/SignInGetResponse.java
  src/main/java/com/tiki/server/common/dto/BaseResponse.java
  src/main/java/com/tiki/server/common/dto/ErrorCodeResponse.java
  src/main/java/com/tiki/server/common/dto/ErrorResponse.java
  src/main/java/com/tiki/server/common/dto/SuccessResponse.java
  src/main/java/com/tiki/server/document/dto/request/DocumentCreateRequest.java
  src/main/java/com/tiki/server/document/dto/request/DocumentsCreateRequest.java
  src/main/java/com/tiki/server/document/dto/response/DeletedDocumentsGetResponse.java
  src/main/java/com/tiki/server/document/dto/response/DocumentsCreateResponse.java
  src/main/java/com/tiki/server/document/dto/response/DocumentsGetResponse.java
  src/main/java/com/tiki/server/drive/dto/DriveGetResponse.java
  src/main/java/com/tiki/server/emailverification/dto/request/CodeVerificationRequest.java
  src/main/java/com/tiki/server/emailverification/dto/request/EmailRequest.java
  src/main/java/com/tiki/server/external/dto/request/PreSignedUrlRequest.java
  src/main/java/com/tiki/server/external/dto/request/S3DeleteRequest.java
  src/main/java/com/tiki/server/external/dto/response/PreSignedUrlResponse.java
  src/main/java/com/tiki/server/folder/dto/request/FolderCreateRequest.java
  src/main/java/com/tiki/server/folder/dto/request/FolderNameUpdateRequest.java
  src/main/java/com/tiki/server/folder/dto/response/FolderCreateResponse.java
  src/main/java/com/tiki/server/folder/dto/response/FoldersGetResponse.java
  src/main/java/com/tiki/server/member/dto/request/MemberProfileCreateRequest.java
  src/main/java/com/tiki/server/member/dto/request/PasswordChangeRequest.java
  src/main/java/com/tiki/server/member/dto/response/BelongTeamsGetResponse.java
  src/main/java/com/tiki/server/member/dto/response/SignInResultGetResponse.java
  src/main/java/com/tiki/server/note/controller/dto/request/NoteFreeCreateRequest.java
  src/main/java/com/tiki/server/note/controller/dto/request/NoteFreeUpdateRequest.java
  src/main/java/com/tiki/server/note/controller/dto/request/NoteTemplateCreateRequest.java
  src/main/java/com/tiki/server/note/controller/dto/request/NoteTemplateUpdateRequest.java
  src/main/java/com/tiki/server/team/dto/request/TeamCreateRequest.java
  src/main/java/com/tiki/server/team/dto/response/CategoriesGetResponse.java
  src/main/java/com/tiki/server/team/dto/response/TeamCreateResponse.java
  src/main/java/com/tiki/server/team/dto/response/TeamGetResponse.java
  src/main/java/com/tiki/server/team/dto/response/TeamsGetResponse.java
  src/main/java/com/tiki/server/team/dto/response/UsageGetResponse.java
  src/main/java/com/tiki/server/timeblock/dto/request/TimeBlockCreateRequest.java
  src/main/java/com/tiki/server/timeblock/dto/response/TimeBlockCreateResponse.java
  src/main/java/com/tiki/server/timeblock/dto/response/TimeBlockDetailGetResponse.java
  src/main/java/com/tiki/server/timeblock/dto/response/TimelineGetResponse.java
Labels: chore

#208 [CHORE] 클라 oas 도입 관련 미적용 이슈 해결
  src/main/java/com/tiki/server/auth/token/entity/Token.java
  src/main/java/com/tiki/server/note/service/dto/request/NoteBase.java
  src/main/java/com/tiki/server/note/service/dto/request/NoteFreeCreateServiceRequest.java
  src/main/java/com/tiki/server/note/service/dto/request/NoteFreeUpdateServiceRequest.java
  src/main/java/com/tiki/server/note/service/dto/request/NoteTemplateCreateServiceRequest.java
  src/main/java/com/tiki/server/note/service/dto/request/NoteTemplateUpdateServiceRequest.java
  src/main/java/com/tiki/server/note/service/dto/response/NoteFreeDetailGetServiceResponse.java
  src/main/java/com/tiki/server/note/service/dto/response/NoteGetResponse.java
  src/main/java/com/tiki/server/note/service/dto/response/NoteListGetServiceResponse.java
  src/main/java/com/tiki/server/note/service/dto/response/NoteTemplateDetailGetServiceResponse.java
  src/main/java/com/tiki/server/team/vo/TeamVO.java
  src/main/java/com/tiki/server/timeblock/service/dto/DocumentTagInfo.java
Labels: chore

#213 [FIX] 팀 생성
  src/main/java/com/tiki/server/team/entity/Team.java
Labels: fix

#217 [CHORE] 팀 정보 수정 로직 분리 및 팀 정보 반환시 팀 이름 변경 날짜 반환
  src/main/java/com/tiki/server/team/controller/TeamController.java
  src/main/java/com/tiki/server/team/dto/request/TeamInformUpdateRequest.java
  src/main/java/com/tiki/server/team/dto/request/TeamInformUpdateServiceRequest.java
  src/main/java/com/tiki/server/team/dto/request/TeamMemberAndTeamInformUpdateServiceRequest.java
  src/main/java/com/tiki/server/team/entity/Team.java
  src/main/java/com/tiki/server/team/message/SuccessMessage.java
  src/main/java/com/tiki/server/team/service/TeamService.java
  src/main/java/com/tiki/server/team/service/dto/response/TeamInformGetResponse.java
Labels: chore
