Repository Team-Tiki/TIKI_SERVER, pull requests merged in 2024-07, with the labels that each got.

#4 [INIT] issue, pull request template 세팅
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
Labels: setting

#7 Init/#6 docker volume
  .github/workflows/CI.yml
  Dockerfile
Labels: setting

#13 [INIT] docker compose 구현
  build.gradle
  docker-compose.yml
  src/main/resources/application-dev.yml
Labels: setting

#15 [INIT] 패키지 구조 및 엔티티 초기 세팅
  .github/workflows/CI.yml
  src/main/java/com/tiki/server/auth/controller/AuthController.java
  src/main/java/com/tiki/server/auth/exception/AuthException.java
  src/main/java/com/tiki/server/auth/message/ErrorCode.java
  src/main/java/com/tiki/server/auth/message/SuccessMessage.java
  src/main/java/com/tiki/server/auth/service/AuthService.java
  src/main/java/com/tiki/server/common/config/JpaAuditingConfig.java
  src/main/java/com/tiki/server/common/config/TimezoneConfig.java
  src/main/java/com/tiki/server/common/dto/BaseResponse.java
  src/main/java/com/tiki/server/common/dto/ErrorResponse.java
  src/main/java/com/tiki/server/common/dto/SuccessResponse.java
  src/main/java/com/tiki/server/common/entity/BaseTime.java
  src/main/java/com/tiki/server/common/handler/ErrorHandler.java
  src/main/java/com/tiki/server/common/support/RepositoryAdapter.java
  src/main/java/com/tiki/server/common/support/StringListConverter.java
  src/main/java/com/tiki/server/controller/ProfileController.java
  src/main/java/com/tiki/server/member/adapter/MemberFinder.java
  src/main/java/com/tiki/server/member/controller/MemberController.java
  src/main/java/com/tiki/server/member/entity/Member.java
  src/main/java/com/tiki/server/member/entity/University.java
  src/main/java/com/tiki/server/member/exception/MemberException.java
  src/main/java/com/tiki/server/member/message/ErrorCode.java
  src/main/java/com/tiki/server/member/message/SuccessMessage.java
  src/main/java/com/tiki/server/member/repository/MemberRepository.java
  src/main/java/com/tiki/server/member/service/MemberService.java
  src/main/java/com/tiki/server/memberteammanager/adapter/MemberTeamManagerFinder.java
  src/main/java/com/tiki/server/memberteammanager/controller/MemberTeamManagerController.java
  src/main/java/com/tiki/server/memberteammanager/entity/MemberTeamManager.java
  src/main/java/com/tiki/server/memberteammanager/entity/Position.java
  src/main/java/com/tiki/server/memberteammanager/exception/MemberTeamManagerException.java
  src/main/java/com/tiki/server/memberteammanager/message/ErrorCode.java
  src/main/java/com/tiki/server/memberteammanager/message/SuccessMessage.java
  src/main/java/com/tiki/server/memberteammanager/repository/MemberTeamManagerRepository.java
  src/main/java/com/tiki/server/memberteammanager/service/MemberTeamManagerService.java
  src/main/java/com/tiki/server/team/adapter/TeamFinder.java
  src/main/java/com/tiki/server/team/controller/TeamController.java
  src/main/java/com/tiki/server/team/entity/Category.java
  src/main/java/com/tiki/server/team/entity/Team.java
  src/main/java/com/tiki/server/team/entity/TeamType.java
  src/main/java/com/tiki/server/team/exception/TeamException.java
  src/main/java/com/tiki/server/team/message/ErrorCode.java
  src/main/java/com/tiki/server/team/message/SuccessMessage.java
  src/main/java/com/tiki/server/team/repository/TeamRepository.java
  src/main/java/com/tiki/server/team/service/TeamService.java
  src/main/java/com/tiki/server/timeblock/adapter/TimeBlockFinder.java
  src/main/java/com/tiki/server/timeblock/controller/TimeBlockController.java
  src/main/java/com/tiki/server/timeblock/entity/TimeBlock.java
  src/main/java/com/tiki/server/timeblock/exception/TimeBlockException.java
  src/main/java/com/tiki/server/timeblock/message/ErrorCode.java
  src/main/java/com/tiki/server/timeblock/message/SuccessMessage.java
  src/main/java/com/tiki/server/timeblock/repository/TimeBlockRepository.java
  src/main/java/com/tiki/server/timeblock/service/TimeBlockService.java
Labels: setting

#21 [INIT] 슬랙 로그 연동
  build.gradle
  src/main/resources/application-dev.yml
  src/main/resources/logback-spring.xml
Labels: setting

#25 [INIT] S3 설정
  build.gradle
  src/main/java/com/tiki/server/common/handler/ErrorHandler.java
  src/main/java/com/tiki/server/external/config/AWSConfig.java
  src/main/java/com/tiki/server/external/exception/ExternalException.java
  src/main/java/com/tiki/server/external/message/ErrorCode.java
  src/main/java/com/tiki/server/external/util/S3Service.java
  src/main/resources/application-dev.yml
Labels: setting

#24 [INIT] Security Config및 JWT 필터 설정
  build.gradle
  src/main/java/com/tiki/server/auth/config/SecurityConfig.java
  src/main/java/com/tiki/server/auth/exception/handler/CustomAccessDeniedHandler.java
  src/main/java/com/tiki/server/auth/exception/handler/CustomAuthenticationEntryPointHandler.java
  src/main/java/com/tiki/server/auth/filter/ExceptionHandlerFilter.java
  src/main/java/com/tiki/server/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/tiki/server/auth/info/AuthenticationResponse.java
  src/main/java/com/tiki/server/auth/jwt/JwtGenerator.java
  src/main/java/com/tiki/server/auth/jwt/JwtProvider.java
  src/main/java/com/tiki/server/auth/jwt/JwtValidationType.java
  src/main/java/com/tiki/server/auth/jwt/JwtValidator.java
  src/main/java/com/tiki/server/auth/jwt/UserAuthentication.java
  src/main/java/com/tiki/server/auth/message/ErrorCode.java
  src/main/java/com/tiki/server/common/Constants.java
  src/main/java/com/tiki/server/team/controller/TeamController.java
  src/main/resources/application-dev.yml
Labels: setting, feat

#31 [HOTFIX] NullPointException 해결
  src/main/java/com/tiki/server/auth/exception/handler/CustomAccessDeniedHandler.java
  src/main/java/com/tiki/server/auth/exception/handler/CustomAuthenticationEntryPointHandler.java
  src/main/java/com/tiki/server/auth/info/AuthenticationResponse.java
Labels: hotfix

#37 [INIT] Swagger 설정
  build.gradle
  src/main/java/com/tiki/server/auth/config/SecurityConfig.java
  src/main/java/com/tiki/server/common/config/SwaggerConfig.java
  src/main/java/com/tiki/server/external/controller/S3Controller.java
  src/main/java/com/tiki/server/external/controller/docs/S3ControllerDocs.java
  src/main/java/com/tiki/server/member/adapter/MemberFinder.java
  src/main/java/com/tiki/server/timeblock/controller/TimeBlockController.java
  src/main/java/com/tiki/server/timeblock/controller/docs/TimeBlockControllerDocs.java
Labels: setting

#36 [FEAT] 회원가입 API 구현
  src/main/java/com/tiki/server/auth/config/EncoderConfig.java
  src/main/java/com/tiki/server/auth/controller/AuthController.java
  src/main/java/com/tiki/server/common/entity/University.java
  src/main/java/com/tiki/server/member/adapter/MemberFinder.java
  src/main/java/com/tiki/server/member/adapter/MemberSaver.java
  src/main/java/com/tiki/server/member/controller/MemberController.java
  src/main/java/com/tiki/server/member/dto/request/MemberProfileCreateRequest.java
  src/main/java/com/tiki/server/member/entity/Member.java
  src/main/java/com/tiki/server/member/entity/University.java
  src/main/java/com/tiki/server/member/exception/MemberException.java
  src/main/java/com/tiki/server/member/message/ErrorCode.java
  src/main/java/com/tiki/server/member/message/SuccessMessage.java
  src/main/java/com/tiki/server/member/repository/MemberRepository.java
  src/main/java/com/tiki/server/member/service/MemberService.java
Labels: feat

#41 [INIT] Cors 설정
  src/main/java/com/tiki/server/auth/config/SecurityConfig.java
  src/main/java/com/tiki/server/common/config/CorsConfig.java
Labels: setting

#46 [HOTFIX] 화이트 리스트 URL 추가
  src/main/java/com/tiki/server/auth/config/SecurityConfig.java
Labels: hotfix

#44 [FEAT] 타임라인 조회
  src/main/java/com/tiki/server/document/adapter/DocumentFinder.java
  src/main/java/com/tiki/server/document/repository/DocumentRepository.java
  src/main/java/com/tiki/server/document/vo/DocumentVO.java
  src/main/java/com/tiki/server/timeblock/adapter/TimeBlockFinder.java
  src/main/java/com/tiki/server/timeblock/controller/TimeBlockController.java
  src/main/java/com/tiki/server/timeblock/controller/docs/TimeBlockControllerDocs.java
  src/main/java/com/tiki/server/timeblock/dto/request/TimeBlockCreateRequest.java
  src/main/java/com/tiki/server/timeblock/dto/response/TimeBlockCreateResponse.java
  src/main/java/com/tiki/server/timeblock/dto/response/TimelineGetResponse.java
  src/main/java/com/tiki/server/timeblock/entity/TimeBlock.java
  src/main/java/com/tiki/server/timeblock/message/SuccessMessage.java
  src/main/java/com/tiki/server/timeblock/repository/TimeBlockRepository.java
  src/main/java/com/tiki/server/timeblock/service/TimeBlockService.java
  src/main/java/com/tiki/server/timeblock/vo/TimeBlockVO.java
Labels: feat

#48 [FEAT] 임시 액세스 토큰 발급 로직
  src/main/java/com/tiki/server/auth/config/SecurityConfig.java
  src/main/java/com/tiki/server/auth/controller/AuthController.java
  src/main/java/com/tiki/server/auth/jwt/JwtGenerator.java
  src/main/java/com/tiki/server/auth/service/AuthService.java
Labels: feat

#52 [HOTFIX] s3 PresignedUrl HTTP Method 변경
  src/main/java/com/tiki/server/external/controller/S3Controller.java
Labels: hotfix

#50 [FEAT] 타임 블록 상세 정보 조회
  src/main/java/com/tiki/server/timeblock/adapter/TimeBlockFinder.java
  src/main/java/com/tiki/server/timeblock/controller/TimeBlockController.java
  src/main/java/com/tiki/server/timeblock/dto/response/TimeBlockDetailGetResponse.java
  src/main/java/com/tiki/server/timeblock/message/ErrorCode.java
  src/main/java/com/tiki/server/timeblock/message/SuccessMessage.java
  src/main/java/com/tiki/server/timeblock/service/TimeBlockService.java
  src/main/java/com/tiki/server/timeblock/vo/TimeBlockVO.java
Labels: feat

#54 [REFACTOR] S3 PresignedUrl Http Method 방식 재변경 및 스웨거 미적용 api 수정
  src/main/java/com/tiki/server/external/controller/S3Controller.java
  src/main/java/com/tiki/server/external/controller/docs/S3ControllerDocs.java
  src/main/java/com/tiki/server/external/util/S3Service.java
  src/main/java/com/tiki/server/timeblock/constant/TimeBlockConstant.java
  src/main/java/com/tiki/server/timeblock/controller/TimeBlockController.java
  src/main/java/com/tiki/server/timeblock/controller/docs/TimeBlockControllerDocs.java
Labels: refactor

#56 [FEAT] 팀 생성
  src/main/java/com/tiki/server/common/entity/University.java
  src/main/java/com/tiki/server/member/adapter/MemberFinder.java
  src/main/java/com/tiki/server/memberteammanager/adapter/MemberTeamManagerSaver.java
  src/main/java/com/tiki/server/memberteammanager/entity/MemberTeamManager.java
  src/main/java/com/tiki/server/team/adapter/TeamSaver.java
  src/main/java/com/tiki/server/team/controller/TeamController.java
  src/main/java/com/tiki/server/team/controller/docs/TeamControllerDocs.java
  src/main/java/com/tiki/server/team/dto/request/TeamCreateRequest.java
  src/main/java/com/tiki/server/team/dto/response/TeamCreateResponse.java
  src/main/java/com/tiki/server/team/entity/Category.java
  src/main/java/com/tiki/server/team/entity/Team.java
  src/main/java/com/tiki/server/team/message/SuccessMessage.java
  src/main/java/com/tiki/server/team/service/TeamService.java
Labels: feat

#57 [FEAT] 회원가입 시 & 비밀번호 변경 시 이메일 인증, 코드 검증 API 추가
  build.gradle
  src/main/java/com/tiki/server/auth/config/SecurityConfig.java
  src/main/java/com/tiki/server/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/tiki/server/common/config/RedisConfig.java
  src/main/java/com/tiki/server/common/handler/ErrorHandler.java
  src/main/java/com/tiki/server/mail/adapter/MailFinder.java
  src/main/java/com/tiki/server/mail/adapter/MailSaver.java
  src/main/java/com/tiki/server/mail/config/MailConfig.java
  src/main/java/com/tiki/server/mail/constants/MailConstants.java
  src/main/java/com/tiki/server/mail/controller/MailController.java
  src/main/java/com/tiki/server/mail/controller/docs/MailControllerDocs.java
  src/main/java/com/tiki/server/mail/dto/request/CodeCheck.java
  src/main/java/com/tiki/server/mail/dto/request/MailRequest.java
  src/main/java/com/tiki/server/mail/entity/Mail.java
  src/main/java/com/tiki/server/mail/exception/MailException.java
  src/main/java/com/tiki/server/mail/message/ErrorCode.java
  src/main/java/com/tiki/server/mail/message/SuccessMessage.java
  src/main/java/com/tiki/server/mail/repository/MailRepository.java
  src/main/java/com/tiki/server/mail/service/MailService.java
  src/main/java/com/tiki/server/member/message/ErrorCode.java
  src/main/java/com/tiki/server/member/service/MemberService.java
  src/main/resources/application-dev.yml
  src/main/resources/images/mail_logo.png
  src/main/resources/templates/certification.html
Labels: feat

#61 [FEAT] 헬스체크 URL 추가
  src/main/java/com/tiki/server/auth/config/SecurityConfig.java
Labels: hotfix

#64 [HOTFIX] 이메일 패스워드 변수 static 삭제
  src/main/java/com/tiki/server/mail/config/MailConfig.java
  src/main/resources/application-dev.yml
Labels: hotfix

#66 [CHORE] REDIS 설정 변경
  src/main/java/com/tiki/server/common/config/RedisConfig.java
  src/main/resources/application-dev.yml
Labels: hotfix

#67 [CHORE] 도커 컴포즈 수정
  docker-compose.yml
  src/main/java/com/tiki/server/member/dto/request/MemberProfileCreateRequest.java
  src/main/java/com/tiki/server/member/service/MemberService.java
Labels: fix

#70 [CHORE] 도커 CD 변경
  .github/workflows/DOCKER-CD.yml
  docker-compose.yml
Labels: hotfix

#71 [HOTFIX] docker-compose 롤백
  .github/workflows/DOCKER-CD.yml
  docker-compose.yml
Labels: hotfix

#74 [HOTFIX] Dockerfile 볼륨 설정 제거
  Dockerfile
Labels: hotfix

#79 [HOTFIX] SecurityConfig 재설정
  src/main/java/com/tiki/server/auth/config/SecurityConfig.java
Labels: feat

#82 [FEAT] 전체 문서 조회
  src/main/java/com/tiki/server/auth/config/SecurityConfig.java
  src/main/java/com/tiki/server/document/adapter/DocumentFinder.java
  src/main/java/com/tiki/server/document/controller/DocumentController.java
  src/main/java/com/tiki/server/document/dto/response/DocumentsGetResponse.java
  src/main/java/com/tiki/server/document/message/ErrorCode.java
  src/main/java/com/tiki/server/document/message/SuccessMessage.java
  src/main/java/com/tiki/server/document/repository/DocumentRepository.java
  src/main/java/com/tiki/server/document/service/DocumentService.java
  src/main/resources/application-dev.yml
Labels: feat

#80 [FEAT] 팀조회 API 추가
  src/main/java/com/tiki/server/team/adapter/TeamFinder.java
  src/main/java/com/tiki/server/team/adapter/TeamSaver.java
  src/main/java/com/tiki/server/team/controller/TeamController.java
  src/main/java/com/tiki/server/team/controller/docs/TeamControllerDocs.java
  src/main/java/com/tiki/server/team/dto/request/TeamCreateRequest.java
  src/main/java/com/tiki/server/team/dto/response/TeamCreateResponse.java
  src/main/java/com/tiki/server/team/dto/response/TeamGetResponse.java
  src/main/java/com/tiki/server/team/dto/response/TeamsGetResponse.java
  src/main/java/com/tiki/server/team/entity/Category.java
  src/main/java/com/tiki/server/team/entity/Group.java
  src/main/java/com/tiki/server/team/message/SuccessMessage.java
  src/main/java/com/tiki/server/team/repository/TeamRepository.java
  src/main/java/com/tiki/server/team/service/TeamService.java
  src/main/java/com/tiki/server/team/vo/TeamVO.java
Labels: feat

#86 [FEAT] 타임 블록 삭제
  src/main/java/com/tiki/server/document/adapter/DocumentDeleter.java
  src/main/java/com/tiki/server/timeblock/adapter/TimeBlockDeleter.java
  src/main/java/com/tiki/server/timeblock/controller/TimeBlockController.java
  src/main/java/com/tiki/server/timeblock/controller/docs/TimeBlockControllerDocs.java
  src/main/java/com/tiki/server/timeblock/service/TimeBlockService.java
Labels: feat

#88 [FEAT] 문서 삭제
  src/main/java/com/tiki/server/document/adapter/DocumentDeleter.java
  src/main/java/com/tiki/server/document/adapter/DocumentFinder.java
  src/main/java/com/tiki/server/document/controller/DocumentController.java
  src/main/java/com/tiki/server/document/controller/docs/DocumentControllerDocs.java
  src/main/java/com/tiki/server/document/repository/DocumentRepository.java
  src/main/java/com/tiki/server/document/service/DocumentService.java
Labels: feat

#89 [FEAT] 왼쪽 사이드바 API구현
  src/main/java/com/tiki/server/member/controller/MemberController.java
  src/main/java/com/tiki/server/member/controller/docs/MemberControllerDocs.java
  src/main/java/com/tiki/server/member/dto/response/BelongTeamsGetResponse.java
  src/main/java/com/tiki/server/member/repository/MemberRepository.java
  src/main/java/com/tiki/server/member/service/MemberService.java
  src/main/java/com/tiki/server/memberteammanager/adapter/MemberTeamManagerFinder.java
  src/main/java/com/tiki/server/memberteammanager/adapter/MemberTeamManagerSaver.java
  src/main/java/com/tiki/server/memberteammanager/controller/MemberTeamManagerController.java
  src/main/java/com/tiki/server/memberteammanager/repository/MemberTeamManagerRepository.java
  src/main/java/com/tiki/server/team/adapter/TeamFinder.java
  src/main/java/com/tiki/server/team/controller/TeamController.java
  src/main/java/com/tiki/server/team/controller/docs/TeamControllerDocs.java
  src/main/java/com/tiki/server/team/message/SuccessMessage.java
  src/main/java/com/tiki/server/team/repository/TeamRepository.java
  src/main/java/com/tiki/server/team/service/TeamService.java
  src/main/java/com/tiki/server/team/vo/TeamVO.java
Labels: feat

#92 [FEAT] 카테고리 조회
  src/main/java/com/tiki/server/team/controller/TeamController.java
  src/main/java/com/tiki/server/team/controller/docs/TeamControllerDocs.java
  src/main/java/com/tiki/server/team/dto/response/CategoriesGetResponse.java
  src/main/java/com/tiki/server/team/entity/Category.java
  src/main/java/com/tiki/server/team/message/SuccessMessage.java
  src/main/java/com/tiki/server/team/service/TeamService.java
  src/main/java/com/tiki/server/timeblock/controller/docs/TimeBlockControllerDocs.java
  src/main/java/com/tiki/server/timeblock/dto/request/TimeBlockCreateRequest.java
  src/main/java/com/tiki/server/timeblock/dto/response/TimelineGetResponse.java
  src/main/java/com/tiki/server/timeblock/entity/BlockType.java
  src/main/java/com/tiki/server/timeblock/entity/TimeBlock.java
  src/main/java/com/tiki/server/timeblock/vo/TimeBlockVO.java
Labels: feat

#93 [HOTFIX] BlockType 설정 누락
  src/main/java/com/tiki/server/timeblock/entity/TimeBlock.java
Labels: hotfix

#94 [HOTFIX] 타임 블록 생성 버그 수정
  src/main/java/com/tiki/server/timeblock/entity/TimeBlock.java
Labels: hotfix

#98 [FEAT] 액세스 토큰 발급
  src/main/java/com/tiki/server/auth/controller/AuthController.java
  src/main/java/com/tiki/server/auth/service/AuthService.java
Labels: feat

#97 [FEAT] 비밀번호 변경 API 추가
  src/main/java/com/tiki/server/member/controller/MemberController.java
  src/main/java/com/tiki/server/member/controller/docs/MemberControllerDocs.java
  src/main/java/com/tiki/server/member/dto/request/PasswordChangeRequest.java
  src/main/java/com/tiki/server/member/entity/Member.java
  src/main/java/com/tiki/server/member/message/SuccessMessage.java
  src/main/java/com/tiki/server/member/service/MemberService.java
Labels: feat

#100 [FIX] 회원가입 로직 수정 및 용어 일치
  src/main/java/com/tiki/server/mail/adapter/MailFinder.java
  src/main/java/com/tiki/server/mail/config/MailConfig.java
  src/main/java/com/tiki/server/mail/constants/MailConstants.java
  src/main/java/com/tiki/server/mail/dto/request/CodeCheck.java
  src/main/java/com/tiki/server/mail/dto/request/MailRequest.java
  src/main/java/com/tiki/server/mail/entity/Mail.java
  src/main/java/com/tiki/server/mail/repository/MailRepository.java
  src/main/java/com/tiki/server/mail/service/MailService.java
  src/main/java/com/tiki/server/member/service/MemberService.java
Labels: fix

#102 [CHORE] 로그인 반환 타입 변경
  src/main/java/com/tiki/server/auth/dto/response/SignInGetResponse.java
  src/main/java/com/tiki/server/auth/service/AuthService.java
Labels: fix

#105 [REFACTOR] 전체 문서 조회 전달 데이터 추가
  src/main/java/com/tiki/server/document/adapter/DocumentFinder.java
  src/main/java/com/tiki/server/document/dto/response/DocumentsGetResponse.java
  src/main/java/com/tiki/server/document/repository/DocumentRepository.java
  src/main/java/com/tiki/server/team/controller/TeamController.java
  src/main/java/com/tiki/server/team/controller/docs/TeamControllerDocs.java
Labels: refactor

#108 [CHORE] cors 배포 url 추가
  src/main/java/com/tiki/server/common/config/CorsConfig.java
Labels: feat

#112 [HOTFIX] 타임라인 조회 버그 수정
  src/main/java/com/tiki/server/timeblock/repository/TimeBlockRepository.java
Labels: hotfix

#114 [HOTFIX] CorsConfig에 서버 도메인 추가
  src/main/java/com/tiki/server/common/config/CorsConfig.java
Labels: hotfix

#116 [HOTFIX] 타임라인 조회 로직 오류 수정
  src/main/java/com/tiki/server/timeblock/repository/TimeBlockRepository.java
Labels: hotfix

#118 [HOTFIX] 타임라인 조회
  src/main/java/com/tiki/server/timeblock/repository/TimeBlockRepository.java
Labels: feat

#120 [HOTFIX] 타임라인 조회 버그 수정
  src/main/java/com/tiki/server/common/config/SwaggerConfig.java
  src/main/java/com/tiki/server/timeblock/repository/TimeBlockRepository.java
Labels: hotfix

#122 [FIX] Security Config 로직 수정
  src/main/java/com/tiki/server/auth/config/SecurityConfig.java
  src/main/java/com/tiki/server/auth/controller/AuthController.java
  src/main/java/com/tiki/server/auth/exception/handler/CustomAccessDeniedHandler.java
  src/main/java/com/tiki/server/auth/exception/handler/CustomAuthenticationEntryPointHandler.java
  src/main/java/com/tiki/server/auth/filter/ExceptionHandlerFilter.java
  src/main/java/com/tiki/server/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/tiki/server/auth/jwt/JwtProvider.java
  src/main/java/com/tiki/server/auth/jwt/JwtValidationType.java
  src/main/java/com/tiki/server/auth/jwt/JwtValidator.java
  src/main/java/com/tiki/server/auth/message/ErrorCode.java
  src/main/java/com/tiki/server/auth/service/AuthService.java
Labels: bug

#126 [HOTFIX] 예외 처리 설정
  src/main/java/com/tiki/server/auth/filter/ExceptionHandlerFilter.java
  src/main/java/com/tiki/server/auth/jwt/JwtValidator.java
  src/main/java/com/tiki/server/auth/message/ErrorCode.java
  src/main/java/com/tiki/server/auth/service/AuthService.java
  src/main/java/com/tiki/server/common/handler/ErrorHandler.java
Labels: hotfix

#131 [REFACTOR] Member 도메인 리팩토링
  src/main/java/com/tiki/server/common/config/CorsConfig.java
  src/main/java/com/tiki/server/member/adapter/MemberFinder.java
  src/main/java/com/tiki/server/member/entity/Member.java
  src/main/java/com/tiki/server/member/service/MemberService.java
Labels: refactor
