Repository Team-Tiki/TIKI_SERVER, pull requests merged in 2024-08, with the labels that each got.

#133 [FIX] 로직수정 및 불필요한 인자 삭제
  src/main/java/com/tiki/server/member/entity/Member.java
  src/main/java/com/tiki/server/member/service/MemberService.java
Labels: fix

#136 [HOTFIX] 도커 컴포즈 redis 이미지 수정
  docker-compose.yml
Labels: hotfix

#138 [CHORE] refresh token 쿠키 설정
  src/main/java/com/tiki/server/auth/controller/AuthController.java
  src/main/java/com/tiki/server/common/support/CookieGenerator.java
  src/main/java/com/tiki/server/member/dto/response/SignInResultGetResponse.java
Labels: feat

#139 [REFACTOR] refresh token 쿠키로 처리
  src/main/java/com/tiki/server/auth/controller/AuthController.java
  src/main/java/com/tiki/server/auth/service/AuthService.java
  src/main/java/com/tiki/server/common/handler/ErrorHandler.java
Labels: refactor

#142 [REFACTOR] jwt 토큰 로직 롤백
  src/main/java/com/tiki/server/auth/controller/AuthController.java
  src/main/java/com/tiki/server/auth/controller/docs/AuthControllerDocs.java
  src/main/java/com/tiki/server/auth/dto/request/SignInRequest.java
  src/main/java/com/tiki/server/auth/service/AuthService.java
  src/main/java/com/tiki/server/common/support/CookieGenerator.java
Labels: refactor

#143 [REFACTOR] 시큐리티 에러 핸들러 수정
  src/main/java/com/tiki/server/auth/config/SecurityConfig.java
  src/main/java/com/tiki/server/auth/exception/handler/CustomAuthenticationEntryPointHandler.java
  src/main/java/com/tiki/server/auth/filter/ExceptionHandlerFilter.java
  src/main/java/com/tiki/server/auth/jwt/JwtValidator.java
  src/main/java/com/tiki/server/auth/message/ErrorCode.java
Labels: refactor

#144 [REFACTOR] 커스텀 에러 코드 적용
  src/main/java/com/tiki/server/auth/controller/AuthController.java
  src/main/java/com/tiki/server/auth/controller/docs/AuthControllerDocs.java
  src/main/java/com/tiki/server/auth/exception/handler/CustomAuthenticationEntryPointHandler.java
  src/main/java/com/tiki/server/auth/filter/ExceptionHandlerFilter.java
  src/main/java/com/tiki/server/auth/info/AuthenticationResponse.java
  src/main/java/com/tiki/server/auth/message/ErrorCode.java
  src/main/java/com/tiki/server/common/dto/ErrorCodeResponse.java
  src/main/java/com/tiki/server/common/handler/ErrorHandler.java
  src/main/java/com/tiki/server/document/message/ErrorCode.java
  src/main/java/com/tiki/server/external/message/ErrorCode.java
  src/main/java/com/tiki/server/mail/message/ErrorCode.java
  src/main/java/com/tiki/server/member/message/ErrorCode.java
Labels: refactor

#146 [REFACTOR] 1차 스프린트 리팩토링
  src/main/java/com/tiki/server/common/config/SwaggerConfig.java
  src/main/java/com/tiki/server/common/entity/Position.java
  src/main/java/com/tiki/server/document/adapter/DocumentDeleter.java
  src/main/java/com/tiki/server/document/adapter/DocumentFinder.java
  src/main/java/com/tiki/server/document/repository/DocumentRepository.java
  src/main/java/com/tiki/server/document/service/DocumentService.java
  src/main/java/com/tiki/server/external/constant/ExternalConstant.java
  src/main/java/com/tiki/server/external/controller/S3Controller.java
  src/main/java/com/tiki/server/external/util/S3Service.java
  src/main/java/com/tiki/server/memberteammanager/entity/MemberTeamManager.java
  src/main/java/com/tiki/server/memberteammanager/message/ErrorCode.java
  src/main/java/com/tiki/server/team/controller/TeamController.java
  src/main/java/com/tiki/server/team/controller/docs/TeamControllerDocs.java
  src/main/java/com/tiki/server/team/dto/request/TeamCreateRequest.java
  src/main/java/com/tiki/server/team/dto/response/TeamCreateResponse.java
  src/main/java/com/tiki/server/team/service/TeamService.java
  src/main/java/com/tiki/server/timeblock/constant/TimeBlockConstant.java
  src/main/java/com/tiki/server/timeblock/message/ErrorCode.java
  src/main/java/com/tiki/server/timeblock/service/TimeBlockService.java
Labels: refactor
