Repository Team-Tiki/TIKI_SERVER, pull requests merged in 2025-01, with the labels that each got.

#220 [FEAT] 파일 생성 api 응답 수정 및 파일 휴지통 관련 버그 수정
  src/main/java/com/tiki/server/document/adapter/DeletedDocumentAdapter.java
  src/main/java/com/tiki/server/document/controller/DocumentController.java
  src/main/java/com/tiki/server/document/controller/docs/DocumentControllerDocs.java
  src/main/java/com/tiki/server/document/dto/response/DocumentsCreateResponse.java
  src/main/java/com/tiki/server/document/entity/DeletedDocument.java
  src/main/java/com/tiki/server/document/service/DocumentService.java
Labels: feat, fix

#222 [CHORE] 소속 팀 조회시 생성일 기준으로 정렬
  src/main/java/com/tiki/server/member/service/MemberService.java
  src/main/java/com/tiki/server/memberteammanager/adapter/MemberTeamManagerFinder.java
  src/main/java/com/tiki/server/memberteammanager/repository/MemberTeamManagerRepository.java
Labels: feat

#224 [CHORE] 스웨거 docs 수정
  src/main/java/com/tiki/server/note/controller/docs/NoteControllerDocs.java
Labels: chore

#226 [CHORE] 노트 스웨거 수정
  src/main/java/com/tiki/server/note/controller/docs/NoteControllerDocs.java
Labels: chore

#228 [FEAT] 전체 타임블록 조회 api 추가
  src/main/java/com/tiki/server/timeblock/adapter/TimeBlockFinder.java
  src/main/java/com/tiki/server/timeblock/controller/TimeBlockController.java
  src/main/java/com/tiki/server/timeblock/controller/docs/TimeBlockControllerDocs.java
  src/main/java/com/tiki/server/timeblock/message/SuccessMessage.java
  src/main/java/com/tiki/server/timeblock/repository/TimeBlockRepository.java
  src/main/java/com/tiki/server/timeblock/service/TimeBlockService.java
  src/main/java/com/tiki/server/timeblock/service/dto/response/AllTimeBlockServiceResponse.java
  src/main/java/com/tiki/server/timeblock/service/dto/response/TImeBlockTaggingResponse.java
Labels: feat

#230 [FEAT] 용량 정보 추가
  src/main/java/com/tiki/server/timeblock/dto/response/TimeBlockDetailGetResponse.java
  src/main/java/com/tiki/server/timeblock/service/dto/DocumentTagInfo.java
Labels: feat

#232 [FEAT] 타임블록 수정
  src/main/java/com/tiki/server/timeblock/controller/TimeBlockController.java
  src/main/java/com/tiki/server/timeblock/controller/docs/TimeBlockControllerDocs.java
  src/main/java/com/tiki/server/timeblock/dto/request/TimeBlockUpdateRequest.java
  src/main/java/com/tiki/server/timeblock/entity/TimeBlock.java
  src/main/java/com/tiki/server/timeblock/message/SuccessMessage.java
  src/main/java/com/tiki/server/timeblock/service/TimeBlockService.java
Labels: feat

#235 [CHORE] 메일 초대 로직 수정
  src/main/java/com/tiki/server/email/emailsender/entity/MailSender.java
  src/main/java/com/tiki/server/email/emailsender/service/EmailSenderService.java
  src/main/resources/templates/invitation.html
Labels: chore

#240 [CHORE] 용량 데이터 타입 변경
  src/main/java/com/tiki/server/document/dto/request/DocumentCreateRequest.java
  src/main/java/com/tiki/server/document/dto/response/DeletedDocumentsGetResponse.java
  src/main/java/com/tiki/server/document/dto/response/DocumentsGetResponse.java
  src/main/java/com/tiki/server/document/entity/DeletedDocument.java
  src/main/java/com/tiki/server/document/entity/Document.java
  src/main/java/com/tiki/server/document/service/DocumentService.java
  src/main/java/com/tiki/server/document/service/dto/response/DocumentTagGetServiceResponse.java
  src/main/java/com/tiki/server/drive/dto/DriveGetResponse.java
  src/main/java/com/tiki/server/team/dto/response/UsageGetResponse.java
  src/main/java/com/tiki/server/team/entity/Subscribe.java
  src/main/java/com/tiki/server/team/entity/Team.java
  src/main/java/com/tiki/server/team/service/TeamService.java
  src/main/java/com/tiki/server/timeblock/dto/response/TimeBlockDetailGetResponse.java
  src/main/java/com/tiki/server/timeblock/service/dto/DocumentTagInfo.java
Labels: chore

#244 [FEAT] 삭제 api 수정
  src/main/java/com/tiki/server/auth/controller/AuthController.java
  src/main/java/com/tiki/server/auth/service/AuthService.java
  src/main/java/com/tiki/server/common/entity/Position.java
  src/main/java/com/tiki/server/document/adapter/DeletedDocumentAdapter.java
  src/main/java/com/tiki/server/document/repository/DeletedDocumentRepository.java
  src/main/java/com/tiki/server/document/service/DocumentService.java
  src/main/java/com/tiki/server/folder/adapter/FolderDeleter.java
  src/main/java/com/tiki/server/folder/repository/FolderRepository.java
  src/main/java/com/tiki/server/folder/service/FolderService.java
  src/main/java/com/tiki/server/member/adapter/MemberDeleter.java
  src/main/java/com/tiki/server/member/controller/MemberController.java
  src/main/java/com/tiki/server/member/message/SuccessMessage.java
  src/main/java/com/tiki/server/member/service/MemberService.java
  src/main/java/com/tiki/server/memberteammanager/entity/MemberTeamManager.java
  src/main/java/com/tiki/server/memberteammanager/message/ErrorCode.java
  src/main/java/com/tiki/server/note/adapter/NoteDeleter.java
  src/main/java/com/tiki/server/note/repository/NoteRepository.java
  src/main/java/com/tiki/server/notedocumentmanager/adapter/NDDeleter.java
  src/main/java/com/tiki/server/notedocumentmanager/repository/NDRepository.java
  src/main/java/com/tiki/server/notetimeblockmanager/adapter/NTBDeleter.java
  src/main/java/com/tiki/server/notetimeblockmanager/repository/NTBRepository.java
  src/main/java/com/tiki/server/team/service/TeamService.java
  src/main/java/com/tiki/server/timeblock/service/TimeBlockService.java
Labels: feat

#246 [CHORE] 스웨거 docs 수정
  src/main/java/com/tiki/server/team/controller/TeamController.java
  src/main/java/com/tiki/server/team/controller/docs/TeamControllerDocs.java
Labels: feat
