Repository Team-Tiki/TIKI_SERVER, pull requests merged in 2025-03, with the labels that each got.

#272 [FIX] 중복 초대 방지 로직 추가
  src/main/java/com/tiki/server/email/emailsender/service/EmailSenderService.java
  src/main/java/com/tiki/server/email/teaminvitation/adapter/TeamInvitationFinder.java
  src/main/java/com/tiki/server/email/teaminvitation/messages/ErrorCode.java
  src/main/java/com/tiki/server/email/teaminvitation/repository/TeamInvitationRepository.java
Labels: fix

#274 [FEAT] PresignedUrl 로직 적용
  src/main/java/com/tiki/server/document/dto/request/DocumentCreateRequest.java
  src/main/java/com/tiki/server/document/entity/DeletedDocument.java
  src/main/java/com/tiki/server/document/entity/Document.java
  src/main/java/com/tiki/server/document/service/dto/response/DocumentTagGetServiceResponse.java
  src/main/java/com/tiki/server/email/teaminvitation/service/TeamInvitationService.java
  src/main/java/com/tiki/server/email/teaminvitation/service/dto/TeamInvitationInformGetResponse.java
  src/main/java/com/tiki/server/external/controller/FileHandlerController.java
  src/main/java/com/tiki/server/external/controller/docs/FileHandlerControllerDocs.java
  src/main/java/com/tiki/server/external/dto/response/PreSignedUrlResponse.java
  src/main/java/com/tiki/server/external/service/FileHandlerService.java
  src/main/java/com/tiki/server/external/util/AwsHandler.java
  src/main/java/com/tiki/server/member/service/MemberService.java
  src/main/java/com/tiki/server/note/constants/NoteConstants.java
  src/main/java/com/tiki/server/note/service/NoteService.java
  src/main/java/com/tiki/server/note/service/dto/response/NoteFreeDetailGetServiceResponse.java
  src/main/java/com/tiki/server/note/service/dto/response/NoteTemplateDetailGetServiceResponse.java
  src/main/java/com/tiki/server/team/constants/TeamConstants.java
  src/main/java/com/tiki/server/team/controller/TeamController.java
  src/main/java/com/tiki/server/team/controller/docs/TeamControllerDocs.java
  src/main/java/com/tiki/server/team/dto/request/TeamCreateRequest.java
  src/main/java/com/tiki/server/team/dto/request/TeamInformUpdateServiceRequest.java
  src/main/java/com/tiki/server/team/dto/response/TeamInformGetResponse.java
  src/main/java/com/tiki/server/team/dto/response/TeamsGetResponse.java
  src/main/java/com/tiki/server/team/entity/Team.java
  src/main/java/com/tiki/server/team/service/TeamService.java
  src/main/java/com/tiki/server/team/service/dto/response/TeamInformGetResponse.java
Labels: feat, refactor

#280 [CHORE] dto 변수명 수정
  src/main/java/com/tiki/server/team/dto/response/TeamInformGetResponse.java
Labels: chore

#281 [FIX] 팀 삭제 시 팀 관련 이미지 삭제 로직 추가
  src/main/java/com/tiki/server/external/util/AwsHandler.java
  src/main/java/com/tiki/server/team/service/TeamService.java
Labels: fix

#283 [FEAT] 휴지통 스케쥴러
  src/main/java/com/tiki/server/auth/dto/response/SignInGetResponse.java
  src/main/java/com/tiki/server/auth/service/AuthService.java
  src/main/java/com/tiki/server/document/adapter/DeletedDocumentAdapter.java
  src/main/java/com/tiki/server/document/constants/DocumentConstants.java
  src/main/java/com/tiki/server/document/repository/DeletedDocumentRepository.java
  src/main/java/com/tiki/server/document/scheduler/DeletedDocumentTrashScheduler.java
  src/main/java/com/tiki/server/email/teaminvitation/scheduler/TeamInvitationScheduler.java
Labels: feat
